<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        // Map slug → objet Role pour réutilisation
		$roleSuperAdmin = Role::where('name', 'superadmin')->firstOrFail();
		$roleAdmin      = Role::where('name', 'admin')->firstOrFail();
		$roleAvocat     = Role::where('name', 'avocat')->firstOrFail();
		$roleSecretaire = Role::where('name', 'secretaire')->firstOrFail();
		$roleStagiaire  = Role::where('name', 'stagiaire')->firstOrFail();
		$roleAgent      = Role::where('name', 'agent')->firstOrFail();

		$roleSuperAdmin = Role::where('name', 'superadmin')->firstOrFail();
		$roleAdmin      = Role::where('name', 'admin')->firstOrFail();
		$roleAvocat     = Role::where('name', 'avocat')->firstOrFail();
		$roleSecretaire = Role::where('name', 'secretaire')->firstOrFail();
		$roleStagiaire  = Role::where('name', 'stagiaire')->firstOrFail();
		$roleAgent      = Role::where('name', 'agent')->firstOrFail();


        $rolesMap = [
            'admin'      => $roleAdmin,
            'avocat'     => $roleAvocat,
            'secretaire' => $roleSecretaire,
            'stagiaire'  => $roleStagiaire,
            'agent'      => $roleAgent,
        ];

        // ── 3. Personnel / Utilisateurs ───────────────────────────────────

        $personnel = [
            [
                'email'               => 'admin@avocatiquewebx.ma',
                'password'            => Hash::make('admin123'),
                'status'              => 'active',
                'matricule'           => 'CLT0001',
                'full_name_fr'        => 'Admin',
                'full_name_ar'        => 'أدمن',
                'abbreviation_fr'     => '',
                'abbreviation_ar'     => '',
                'fonction'            => 'Avocat Titulaire Seniors',
                'grade_avocat'        => 'Agréé près la Cour de Cassation',
                'departement'         => 'Cabinet',
                'address_fr'          => '12 Rue des Avocats, Casablanca',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'AB123456',
                'date_entree'         => '2020-01-01',
                'valeur_par_defaut'   => true,
                'classement'          => 1,
                'avocat_proprietaire' => true,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0661000001',
                'tarif_journalier'    => 0.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'admin',
                'is_admin'            => true,
                'tfa_enabled'         => false,
                'roles'               => ['admin'],
            ],
            [
                'email'               => 'karim@avocatiquewebx.ma',
                'password'            => Hash::make('avocat123'),
                'status'              => 'active',
                'matricule'           => 'CLT0002',
                'full_name_fr'        => 'Me. Karim Benali',
                'full_name_ar'        => 'ذ/ كريم بنعلي',
                'abbreviation_fr'     => 'K.B.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Avocat Titulaire Seniors',
                'grade_avocat'        => "Agréé près la Cour d'Appel",
                'departement'         => 'Dép-Assurances',
                'address_fr'          => '45 Bd Zerktouni, Casablanca',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'BE789012',
                'date_entree'         => '2021-03-15',
                'valeur_par_defaut'   => false,
                'classement'          => 2,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0661000002',
                'tarif_journalier'    => 1500.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'k.benali',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['avocat'],
            ],
            [
                'email'               => 'sara@avocatiquewebx.ma',
                'password'            => Hash::make('sara1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0003',
                'full_name_fr'        => 'Sara Bouazza',
                'full_name_ar'        => 'سارة بوعزة',
                'abbreviation_fr'     => 'S.B.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Secrétaire',
                'grade_avocat'        => '',
                'departement'         => 'Cabinet',
                'address_fr'          => '8 Rue Ibn Sina, Rabat',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'CD345678',
                'date_entree'         => '2022-06-01',
                'valeur_par_defaut'   => false,
                'classement'          => 3,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0662000003',
                'tarif_journalier'    => 0.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 's.bouazza',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['secretaire'],
            ],
            [
                'email'               => 'youssef@avocatiquewebx.ma',
                'password'            => Hash::make('youssef1234'),
                'status'              => 'inactive',
                'matricule'           => 'CLT0004',
                'full_name_fr'        => 'Youssef Moussaoui',
                'full_name_ar'        => 'يوسف موساوي',
                'abbreviation_fr'     => 'Y.M.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Stagiaire',
                'grade_avocat'        => 'Stagiaire',
                'departement'         => 'Dép-Assurances',
                'address_fr'          => '',
                'address_ar'          => '',
                'langue'              => 'ar',
                'rib'                 => '',
                'cin'                 => 'EF901234',
                'date_entree'         => '2023-09-01',
                'valeur_par_defaut'   => false,
                'classement'          => 4,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0663000004',
                'tarif_journalier'    => 0.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'y.moussaoui',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['stagiaire'],
            ],
            [
                'email'               => 'fatima@avocatiquewebx.ma',
                'password'            => Hash::make('fatima1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0005',
                'full_name_fr'        => 'Me. Fatima Zahri',
                'full_name_ar'        => 'ذة/ فاطمة الزهري',
                'abbreviation_fr'     => 'F.Z.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Avocat Titulaire',
                'grade_avocat'        => "Agréé près la Cour d'Appel",
                'departement'         => 'Département-Risques Divers',
                'address_fr'          => '23 Av Hassan II, Fès',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'GH567890',
                'date_entree'         => '2019-05-10',
                'valeur_par_defaut'   => false,
                'classement'          => 5,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0664000005',
                'tarif_journalier'    => 2000.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'f.zahri',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['avocat'],
            ],
            [
                'email'               => 'omar@avocatiquewebx.ma',
                'password'            => Hash::make('omar1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0006',
                'full_name_fr'        => 'Omar El Fassi',
                'full_name_ar'        => 'عمر الفاسي',
                'abbreviation_fr'     => 'O.F.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Avocat Collaborateur',
                'grade_avocat'        => "Agréé près la Cour d'Appel",
                'departement'         => 'Département-Auto',
                'address_fr'          => '56 Rue Allal Ben Abdellah, Marrakech',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'IJ123789',
                'date_entree'         => '2022-01-20',
                'valeur_par_defaut'   => false,
                'classement'          => 6,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0665000006',
                'tarif_journalier'    => 1200.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'o.elfassi',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['avocat'],
            ],
            [
                'email'               => 'amina@avocatiquewebx.ma',
                'password'            => Hash::make('amina1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0007',
                'full_name_fr'        => 'Amina Rifi',
                'full_name_ar'        => 'أمينة الريفي',
                'abbreviation_fr'     => 'A.R.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Secrétaire',
                'grade_avocat'        => '',
                'departement'         => 'Dép-Assurances',
                'address_fr'          => '3 Rue de la Liberté, Tanger',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'KL456012',
                'date_entree'         => '2023-02-14',
                'valeur_par_defaut'   => false,
                'classement'          => 7,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0666000007',
                'tarif_journalier'    => 0.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'a.rifi',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['secretaire'],
            ],
            [
                'email'               => 'mehdi@avocatiquewebx.ma',
                'password'            => Hash::make('mehdi1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0008',
                'full_name_fr'        => 'Me. Mehdi Tazi',
                'full_name_ar'        => 'ذ/ مهدي التازي',
                'abbreviation_fr'     => 'M.T.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Avocat Titulaire Seniors',
                'grade_avocat'        => 'Agréé près la Cour de Cassation',
                'departement'         => 'Cabinet',
                'address_fr'          => '100 Bd Mohammed V, Casablanca',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'MN789345',
                'date_entree'         => '2018-11-05',
                'valeur_par_defaut'   => false,
                'classement'          => 8,
                'avocat_proprietaire' => true,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0667000008',
                'tarif_journalier'    => 2500.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'm.tazi',
                'is_admin'            => true,
                'tfa_enabled'         => false,
                'roles'               => ['admin', 'avocat'],
            ],
            [
                'email'               => 'hanane@avocatiquewebx.ma',
                'password'            => Hash::make('hanane1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0009',
                'full_name_fr'        => 'Hanane Idrissi',
                'full_name_ar'        => 'حنان الإدريسي',
                'abbreviation_fr'     => 'H.I.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Agent',
                'grade_avocat'        => '',
                'departement'         => 'Département-Informatique',
                'address_fr'          => '15 Rue Oued Fès, Meknès',
                'address_ar'          => '',
                'langue'              => 'ar',
                'rib'                 => '',
                'cin'                 => 'OP012678',
                'date_entree'         => '2024-01-10',
                'valeur_par_defaut'   => false,
                'classement'          => 9,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0668000009',
                'tarif_journalier'    => 0.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'h.idrissi',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['agent'],
            ],
            [
                'email'               => 'rachid@avocatiquewebx.ma',
                'password'            => Hash::make('rachid1234'),
                'status'              => 'active',
                'matricule'           => 'CLT0010',
                'full_name_fr'        => 'Me. Rachid Alaoui',
                'full_name_ar'        => 'ذ/ رشيد العلوي',
                'abbreviation_fr'     => 'R.A.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Avocat Titulaire',
                'grade_avocat'        => 'Agréé près la Cour de Cassation',
                'departement'         => 'Département-Risques Divers',
                'address_fr'          => '77 Av des FAR, Casablanca',
                'address_ar'          => '',
                'langue'              => 'fr',
                'rib'                 => '',
                'cin'                 => 'QR345901',
                'date_entree'         => '2020-07-22',
                'valeur_par_defaut'   => false,
                'classement'          => 10,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0669000010',
                'tarif_journalier'    => 1800.00,
                'observation'         => '',
                'photo'               => '',
                'login'               => 'r.alaoui',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['avocat'],
            ],
            [
                'email'               => 'nadia@avocatiquewebx.ma',
                'password'            => Hash::make('nadia1234'),
                'status'              => 'inactive',
                'matricule'           => 'CLT0011',
                'full_name_fr'        => 'Nadia Chraibi',
                'full_name_ar'        => 'نادية الشرايبي',
                'abbreviation_fr'     => 'N.C.',
                'abbreviation_ar'     => '',
                'fonction'            => 'Stagiaire',
                'grade_avocat'        => 'Stagiaire',
                'departement'         => 'Cabinet',
                'address_fr'          => '5 Rue Moulay Ismail, Rabat',
                'address_ar'          => '',
                'langue'              => 'en',
                'rib'                 => '',
                'cin'                 => 'ST678234',
                'date_entree'         => '2025-01-15',
                'valeur_par_defaut'   => false,
                'classement'          => 11,
                'avocat_proprietaire' => false,
                'couleur_fond'        => '#ffffff',
                'couleur_texte'       => '#73879c',
                'telephone'           => '0670000011',
                'tarif_journalier'    => 0.00,
                'observation'         => 'En attente de validation',
                'photo'               => '',
                'login'               => 'n.chraibi',
                'is_admin'            => false,
                'tfa_enabled'         => false,
                'roles'               => ['stagiaire'],
            ],
        ];

        foreach ($personnel as $data) {
            $roles = $data['roles'];
            unset($data['roles']);

            $user = User::firstOrCreate(
                ['email' => $data['email']],
                $data
            );

            $roleIds = collect($roles)
                ->map(fn($slug) => $rolesMap[$slug] ?? null)
                ->filter()
                ->pluck('id')
                ->toArray();

            $user->roles()->syncWithoutDetaching($roleIds);
        }
    }
}
